use std::sync::{Arc, LazyLock};

use crate::{Lang, LangInner};

macro_rules! define_langs {
    (
        $(
            $fn_name:ident => {
                feature: $feature:literal,
                name: $name:literal,
                ts_lang: $ts_lang:expr,
                node_types_key: $node_types_key:literal,
                names: [$($alias:literal),* $(,)?],
                extensions: [$($ext:literal),* $(,)?] $(,)?
            }
        ),* $(,)?
    ) => {
        // Generate NodeTypes statics via proc macro
        $(
            #[cfg(feature = $feature)]
            plotnik_macros::generate_node_types!($node_types_key);
        )*

        // Generate static Lang definitions with LazyLock
        $(
            #[cfg(feature = $feature)]
            pub fn $fn_name() -> Lang {
                paste::paste! {
                    static LANG: LazyLock<Lang> = LazyLock::new(|| {
                        Arc::new(LangInner::new_static(
                            $name,
                            $ts_lang.into(),
                            &[<$node_types_key:upper _NODE_TYPES>],
                        ))
                    });
                }
                Arc::clone(&LANG)
            }
        )*

        pub fn from_name(s: &str) -> Option<Lang> {
            match s.to_ascii_lowercase().as_str() {
                $(
                    #[cfg(feature = $feature)]
                    $($alias)|* => Some($fn_name()),
                )*
                _ => None,
            }
        }

        #[allow(unreachable_patterns)]
        pub fn from_ext(ext: &str) -> Option<Lang> {
            match ext.to_ascii_lowercase().as_str() {
                $(
                    #[cfg(feature = $feature)]
                    $($ext)|* => Some($fn_name()),
                )*
                _ => None,
            }
        }

        pub fn all() -> Vec<Lang> {
            vec![
                $(
                    #[cfg(feature = $feature)]
                    $fn_name(),
                )*
            ]
        }
    };
}

define_langs! {
    ada => {
        feature: "lang-ada",
        name: "ada",
        ts_lang: arborium_ada::language(),
        node_types_key: "ada",
        names: ["ada"],
        extensions: ["ada", "adb", "ads"],
    },
    agda => {
        feature: "lang-agda",
        name: "agda",
        ts_lang: arborium_agda::language(),
        node_types_key: "agda",
        names: ["agda"],
        extensions: ["agda"],
    },
    asciidoc => {
        feature: "lang-asciidoc",
        name: "asciidoc",
        ts_lang: arborium_asciidoc::language(),
        node_types_key: "asciidoc",
        names: ["asciidoc", "adoc"],
        extensions: ["adoc", "asciidoc", "asc"],
    },
    asm => {
        feature: "lang-asm",
        name: "asm",
        ts_lang: arborium_asm::language(),
        node_types_key: "asm",
        names: ["asm", "assembly"],
        extensions: ["asm", "s"],
    },
    awk => {
        feature: "lang-awk",
        name: "awk",
        ts_lang: arborium_awk::language(),
        node_types_key: "awk",
        names: ["awk", "gawk", "mawk", "nawk"],
        extensions: ["awk"],
    },
    bash => {
        feature: "lang-bash",
        name: "bash",
        ts_lang: arborium_bash::language(),
        node_types_key: "bash",
        names: ["bash", "sh", "shell"],
        extensions: ["sh", "bash"],
    },
    batch => {
        feature: "lang-batch",
        name: "batch",
        ts_lang: arborium_batch::language(),
        node_types_key: "batch",
        names: ["batch", "bat", "cmd"],
        extensions: ["bat", "cmd"],
    },
    c => {
        feature: "lang-c",
        name: "c",
        ts_lang: arborium_c::language(),
        node_types_key: "c",
        names: ["c"],
        extensions: ["c", "h"],
    },
    caddy => {
        feature: "lang-caddy",
        name: "caddy",
        ts_lang: arborium_caddy::language(),
        node_types_key: "caddy",
        names: ["caddy", "caddyfile"],
        extensions: ["caddyfile"],
    },
    capnp => {
        feature: "lang-capnp",
        name: "capnp",
        ts_lang: arborium_capnp::language(),
        node_types_key: "capnp",
        names: ["capnp", "capnproto"],
        extensions: ["capnp"],
    },
    clojure => {
        feature: "lang-clojure",
        name: "clojure",
        ts_lang: arborium_clojure::language(),
        node_types_key: "clojure",
        names: ["clojure", "clj"],
        extensions: ["clj", "cljs", "cljc", "edn"],
    },
    cmake => {
        feature: "lang-cmake",
        name: "cmake",
        ts_lang: arborium_cmake::language(),
        node_types_key: "cmake",
        names: ["cmake"],
        extensions: ["cmake"],
    },
    commonlisp => {
        feature: "lang-commonlisp",
        name: "commonlisp",
        ts_lang: arborium_commonlisp::language(),
        node_types_key: "commonlisp",
        names: ["commonlisp", "common-lisp", "lisp", "cl"],
        extensions: ["lisp", "lsp", "cl"],
    },
    cpp => {
        feature: "lang-cpp",
        name: "cpp",
        ts_lang: arborium_cpp::language(),
        node_types_key: "cpp",
        names: ["cpp", "c++", "cxx", "cc"],
        extensions: ["cpp", "cc", "cxx", "hpp", "hh", "hxx", "h++", "c++"],
    },
    csharp => {
        feature: "lang-c-sharp",
        name: "c_sharp",
        ts_lang: arborium_c_sharp::language(),
        node_types_key: "c_sharp",
        names: ["csharp", "c#", "cs", "c_sharp"],
        extensions: ["cs"],
    },
    css => {
        feature: "lang-css",
        name: "css",
        ts_lang: arborium_css::language(),
        node_types_key: "css",
        names: ["css"],
        extensions: ["css"],
    },
    d => {
        feature: "lang-d",
        name: "d",
        ts_lang: arborium_d::language(),
        node_types_key: "d",
        names: ["d", "dlang"],
        extensions: ["d"],
    },
    dart => {
        feature: "lang-dart",
        name: "dart",
        ts_lang: arborium_dart::language(),
        node_types_key: "dart",
        names: ["dart"],
        extensions: ["dart"],
    },
    devicetree => {
        feature: "lang-devicetree",
        name: "devicetree",
        ts_lang: arborium_devicetree::language(),
        node_types_key: "devicetree",
        names: ["devicetree", "dts"],
        extensions: ["dts", "dtsi"],
    },
    diff => {
        feature: "lang-diff",
        name: "diff",
        ts_lang: arborium_diff::language(),
        node_types_key: "diff",
        names: ["diff", "patch"],
        extensions: ["diff", "patch"],
    },
    dockerfile => {
        feature: "lang-dockerfile",
        name: "dockerfile",
        ts_lang: arborium_dockerfile::language(),
        node_types_key: "dockerfile",
        names: ["dockerfile", "docker"],
        extensions: ["dockerfile"],
    },
    dot => {
        feature: "lang-dot",
        name: "dot",
        ts_lang: arborium_dot::language(),
        node_types_key: "dot",
        names: ["dot", "graphviz"],
        extensions: ["dot", "gv"],
    },
    elisp => {
        feature: "lang-elisp",
        name: "elisp",
        ts_lang: arborium_elisp::language(),
        node_types_key: "elisp",
        names: ["elisp", "emacs-lisp"],
        extensions: ["el"],
    },
    elixir => {
        feature: "lang-elixir",
        name: "elixir",
        ts_lang: arborium_elixir::language(),
        node_types_key: "elixir",
        names: ["elixir", "ex"],
        extensions: ["ex", "exs"],
    },
    elm => {
        feature: "lang-elm",
        name: "elm",
        ts_lang: arborium_elm::language(),
        node_types_key: "elm",
        names: ["elm"],
        extensions: ["elm"],
    },
    erlang => {
        feature: "lang-erlang",
        name: "erlang",
        ts_lang: arborium_erlang::language(),
        node_types_key: "erlang",
        names: ["erlang", "erl"],
        extensions: ["erl", "hrl"],
    },
    fish => {
        feature: "lang-fish",
        name: "fish",
        ts_lang: arborium_fish::language(),
        node_types_key: "fish",
        names: ["fish"],
        extensions: ["fish"],
    },
    fsharp => {
        feature: "lang-fsharp",
        name: "fsharp",
        ts_lang: arborium_fsharp::language(),
        node_types_key: "fsharp",
        names: ["fsharp", "f#", "fs"],
        extensions: ["fs", "fsi", "fsx"],
    },
    gleam => {
        feature: "lang-gleam",
        name: "gleam",
        ts_lang: arborium_gleam::language(),
        node_types_key: "gleam",
        names: ["gleam"],
        extensions: ["gleam"],
    },
    glsl => {
        feature: "lang-glsl",
        name: "glsl",
        ts_lang: arborium_glsl::language(),
        node_types_key: "glsl",
        names: ["glsl"],
        extensions: ["glsl", "vert", "frag", "geom", "tesc", "tese", "comp"],
    },
    go => {
        feature: "lang-go",
        name: "go",
        ts_lang: arborium_go::language(),
        node_types_key: "go",
        names: ["go", "golang"],
        extensions: ["go"],
    },
    graphql => {
        feature: "lang-graphql",
        name: "graphql",
        ts_lang: arborium_graphql::language(),
        node_types_key: "graphql",
        names: ["graphql", "gql"],
        extensions: ["graphql", "gql"],
    },
    groovy => {
        feature: "lang-groovy",
        name: "groovy",
        ts_lang: arborium_groovy::language(),
        node_types_key: "groovy",
        names: ["groovy", "gradle"],
        extensions: ["groovy", "gradle", "gvy", "gy", "gsh"],
    },
    haskell => {
        feature: "lang-haskell",
        name: "haskell",
        ts_lang: arborium_haskell::language(),
        node_types_key: "haskell",
        names: ["haskell", "hs"],
        extensions: ["hs", "lhs"],
    },
    hcl => {
        feature: "lang-hcl",
        name: "hcl",
        ts_lang: arborium_hcl::language(),
        node_types_key: "hcl",
        names: ["hcl", "terraform", "tf"],
        extensions: ["hcl", "tf", "tfvars"],
    },
    hlsl => {
        feature: "lang-hlsl",
        name: "hlsl",
        ts_lang: arborium_hlsl::language(),
        node_types_key: "hlsl",
        names: ["hlsl"],
        extensions: ["hlsl", "hlsli", "fx"],
    },
    html => {
        feature: "lang-html",
        name: "html",
        ts_lang: arborium_html::language(),
        node_types_key: "html",
        names: ["html", "htm"],
        extensions: ["html", "htm"],
    },
    idris => {
        feature: "lang-idris",
        name: "idris",
        ts_lang: arborium_idris::language(),
        node_types_key: "idris",
        names: ["idris"],
        extensions: ["idr"],
    },
    ini => {
        feature: "lang-ini",
        name: "ini",
        ts_lang: arborium_ini::language(),
        node_types_key: "ini",
        names: ["ini"],
        extensions: ["ini", "cfg", "conf"],
    },
    java => {
        feature: "lang-java",
        name: "java",
        ts_lang: arborium_java::language(),
        node_types_key: "java",
        names: ["java"],
        extensions: ["java"],
    },
    javascript => {
        feature: "lang-javascript",
        name: "javascript",
        ts_lang: arborium_javascript::language(),
        node_types_key: "javascript",
        names: ["javascript", "js", "jsx", "ecmascript", "es"],
        extensions: ["js", "mjs", "cjs", "jsx"],
    },
    jinja2 => {
        feature: "lang-jinja2",
        name: "jinja2",
        ts_lang: arborium_jinja2::language(),
        node_types_key: "jinja2",
        names: ["jinja2", "jinja"],
        extensions: ["j2", "jinja", "jinja2"],
    },
    jq => {
        feature: "lang-jq",
        name: "jq",
        ts_lang: arborium_jq::language(),
        node_types_key: "jq",
        names: ["jq"],
        extensions: ["jq"],
    },
    json => {
        feature: "lang-json",
        name: "json",
        ts_lang: arborium_json::language(),
        node_types_key: "json",
        names: ["json"],
        extensions: ["json"],
    },
    julia => {
        feature: "lang-julia",
        name: "julia",
        ts_lang: arborium_julia::language(),
        node_types_key: "julia",
        names: ["julia", "jl"],
        extensions: ["jl"],
    },
    kdl => {
        feature: "lang-kdl",
        name: "kdl",
        ts_lang: arborium_kdl::language(),
        node_types_key: "kdl",
        names: ["kdl"],
        extensions: ["kdl"],
    },
    kotlin => {
        feature: "lang-kotlin",
        name: "kotlin",
        ts_lang: arborium_kotlin::language(),
        node_types_key: "kotlin",
        names: ["kotlin", "kt"],
        extensions: ["kt", "kts"],
    },
    lean => {
        feature: "lang-lean",
        name: "lean",
        ts_lang: arborium_lean::language(),
        node_types_key: "lean",
        names: ["lean", "lean4"],
        extensions: ["lean"],
    },
    lua => {
        feature: "lang-lua",
        name: "lua",
        ts_lang: arborium_lua::language(),
        node_types_key: "lua",
        names: ["lua"],
        extensions: ["lua"],
    },
    markdown => {
        feature: "lang-markdown",
        name: "markdown",
        ts_lang: arborium_markdown::language(),
        node_types_key: "markdown",
        names: ["markdown", "md"],
        extensions: ["md", "markdown"],
    },
    matlab => {
        feature: "lang-matlab",
        name: "matlab",
        ts_lang: arborium_matlab::language(),
        node_types_key: "matlab",
        names: ["matlab", "octave"],
        extensions: ["m"],
    },
    meson => {
        feature: "lang-meson",
        name: "meson",
        ts_lang: arborium_meson::language(),
        node_types_key: "meson",
        names: ["meson"],
        extensions: ["meson"],
    },
    nginx => {
        feature: "lang-nginx",
        name: "nginx",
        ts_lang: arborium_nginx::language(),
        node_types_key: "nginx",
        names: ["nginx"],
        extensions: ["nginx"],
    },
    ninja => {
        feature: "lang-ninja",
        name: "ninja",
        ts_lang: arborium_ninja::language(),
        node_types_key: "ninja",
        names: ["ninja"],
        extensions: ["ninja"],
    },
    nix => {
        feature: "lang-nix",
        name: "nix",
        ts_lang: arborium_nix::language(),
        node_types_key: "nix",
        names: ["nix"],
        extensions: ["nix"],
    },
    objc => {
        feature: "lang-objc",
        name: "objc",
        ts_lang: arborium_objc::language(),
        node_types_key: "objc",
        names: ["objc", "objective-c", "objectivec"],
        extensions: ["m", "mm"],
    },
    ocaml => {
        feature: "lang-ocaml",
        name: "ocaml",
        ts_lang: arborium_ocaml::language(),
        node_types_key: "ocaml",
        names: ["ocaml", "ml"],
        extensions: ["ml", "mli"],
    },
    perl => {
        feature: "lang-perl",
        name: "perl",
        ts_lang: arborium_perl::language(),
        node_types_key: "perl",
        names: ["perl", "pl"],
        extensions: ["pl", "pm"],
    },
    php => {
        feature: "lang-php",
        name: "php",
        ts_lang: arborium_php::language(),
        node_types_key: "php",
        names: ["php"],
        extensions: ["php"],
    },
    postscript => {
        feature: "lang-postscript",
        name: "postscript",
        ts_lang: arborium_postscript::language(),
        node_types_key: "postscript",
        names: ["postscript", "ps"],
        extensions: ["ps", "eps"],
    },
    powershell => {
        feature: "lang-powershell",
        name: "powershell",
        ts_lang: arborium_powershell::language(),
        node_types_key: "powershell",
        names: ["powershell", "pwsh", "ps1"],
        extensions: ["ps1", "psm1", "psd1"],
    },
    prolog => {
        feature: "lang-prolog",
        name: "prolog",
        ts_lang: arborium_prolog::language(),
        node_types_key: "prolog",
        names: ["prolog"],
        extensions: ["pl", "pro"],
    },
    python => {
        feature: "lang-python",
        name: "python",
        ts_lang: arborium_python::language(),
        node_types_key: "python",
        names: ["python", "py"],
        extensions: ["py", "pyi", "pyw"],
    },
    query => {
        feature: "lang-query",
        name: "query",
        ts_lang: arborium_query::language(),
        node_types_key: "query",
        names: ["query", "scm"],
        extensions: ["scm"],
    },
    r => {
        feature: "lang-r",
        name: "r",
        ts_lang: arborium_r::language(),
        node_types_key: "r",
        names: ["r", "rlang"],
        extensions: ["r", "R"],
    },
    rescript => {
        feature: "lang-rescript",
        name: "rescript",
        ts_lang: arborium_rescript::language(),
        node_types_key: "rescript",
        names: ["rescript", "res"],
        extensions: ["res", "resi"],
    },
    ron => {
        feature: "lang-ron",
        name: "ron",
        ts_lang: arborium_ron::language(),
        node_types_key: "ron",
        names: ["ron"],
        extensions: ["ron"],
    },
    ruby => {
        feature: "lang-ruby",
        name: "ruby",
        ts_lang: arborium_ruby::language(),
        node_types_key: "ruby",
        names: ["ruby", "rb"],
        extensions: ["rb", "rake", "gemspec"],
    },
    rust => {
        feature: "lang-rust",
        name: "rust",
        ts_lang: arborium_rust::language(),
        node_types_key: "rust",
        names: ["rust", "rs"],
        extensions: ["rs"],
    },
    scala => {
        feature: "lang-scala",
        name: "scala",
        ts_lang: arborium_scala::language(),
        node_types_key: "scala",
        names: ["scala"],
        extensions: ["scala", "sc"],
    },
    scheme => {
        feature: "lang-scheme",
        name: "scheme",
        ts_lang: arborium_scheme::language(),
        node_types_key: "scheme",
        names: ["scheme", "racket"],
        extensions: ["scm", "ss", "rkt"],
    },
    scss => {
        feature: "lang-scss",
        name: "scss",
        ts_lang: arborium_scss::language(),
        node_types_key: "scss",
        names: ["scss", "sass"],
        extensions: ["scss", "sass"],
    },
    sparql => {
        feature: "lang-sparql",
        name: "sparql",
        ts_lang: arborium_sparql::language(),
        node_types_key: "sparql",
        names: ["sparql"],
        extensions: ["sparql", "rq"],
    },
    sql => {
        feature: "lang-sql",
        name: "sql",
        ts_lang: arborium_sql::language(),
        node_types_key: "sql",
        names: ["sql"],
        extensions: ["sql"],
    },
    ssh_config => {
        feature: "lang-ssh-config",
        name: "ssh_config",
        ts_lang: arborium_ssh_config::language(),
        node_types_key: "ssh_config",
        names: ["ssh-config", "ssh_config", "sshconfig"],
        extensions: ["ssh_config"],
    },
    starlark => {
        feature: "lang-starlark",
        name: "starlark",
        ts_lang: arborium_starlark::language(),
        node_types_key: "starlark",
        names: ["starlark", "bazel", "bzl"],
        extensions: ["bzl", "bazel"],
    },
    svelte => {
        feature: "lang-svelte",
        name: "svelte",
        ts_lang: arborium_svelte::language(),
        node_types_key: "svelte",
        names: ["svelte"],
        extensions: ["svelte"],
    },
    swift => {
        feature: "lang-swift",
        name: "swift",
        ts_lang: arborium_swift::language(),
        node_types_key: "swift",
        names: ["swift"],
        extensions: ["swift"],
    },
    textproto => {
        feature: "lang-textproto",
        name: "textproto",
        ts_lang: arborium_textproto::language(),
        node_types_key: "textproto",
        names: ["textproto", "pbtxt"],
        extensions: ["textproto", "pbtxt"],
    },
    thrift => {
        feature: "lang-thrift",
        name: "thrift",
        ts_lang: arborium_thrift::language(),
        node_types_key: "thrift",
        names: ["thrift"],
        extensions: ["thrift"],
    },
    tlaplus => {
        feature: "lang-tlaplus",
        name: "tlaplus",
        ts_lang: arborium_tlaplus::language(),
        node_types_key: "tlaplus",
        names: ["tlaplus", "tla+", "tla"],
        extensions: ["tla"],
    },
    toml => {
        feature: "lang-toml",
        name: "toml",
        ts_lang: arborium_toml::language(),
        node_types_key: "toml",
        names: ["toml"],
        extensions: ["toml"],
    },
    tsx => {
        feature: "lang-tsx",
        name: "tsx",
        ts_lang: arborium_tsx::language(),
        node_types_key: "tsx",
        names: ["tsx"],
        extensions: ["tsx"],
    },
    typescript => {
        feature: "lang-typescript",
        name: "typescript",
        ts_lang: arborium_typescript::language(),
        node_types_key: "typescript",
        names: ["typescript", "ts"],
        extensions: ["ts", "mts", "cts"],
    },
    typst => {
        feature: "lang-typst",
        name: "typst",
        ts_lang: arborium_typst::language(),
        node_types_key: "typst",
        names: ["typst"],
        extensions: ["typ"],
    },
    uiua => {
        feature: "lang-uiua",
        name: "uiua",
        ts_lang: arborium_uiua::language(),
        node_types_key: "uiua",
        names: ["uiua"],
        extensions: ["ua"],
    },
    vb => {
        feature: "lang-vb",
        name: "vb",
        ts_lang: arborium_vb::language(),
        node_types_key: "vb",
        names: ["vb", "vbnet", "visualbasic"],
        extensions: ["vb"],
    },
    verilog => {
        feature: "lang-verilog",
        name: "verilog",
        ts_lang: arborium_verilog::language(),
        node_types_key: "verilog",
        names: ["verilog", "v"],
        extensions: ["v", "sv"],
    },
    vhdl => {
        feature: "lang-vhdl",
        name: "vhdl",
        ts_lang: arborium_vhdl::language(),
        node_types_key: "vhdl",
        names: ["vhdl"],
        extensions: ["vhd", "vhdl"],
    },
    vim => {
        feature: "lang-vim",
        name: "vim",
        ts_lang: arborium_vim::language(),
        node_types_key: "vim",
        names: ["vim", "vimscript"],
        extensions: ["vim"],
    },
    vue => {
        feature: "lang-vue",
        name: "vue",
        ts_lang: arborium_vue::language(),
        node_types_key: "vue",
        names: ["vue"],
        extensions: ["vue"],
    },
    wit => {
        feature: "lang-wit",
        name: "wit",
        ts_lang: arborium_wit::language(),
        node_types_key: "wit",
        names: ["wit"],
        extensions: ["wit"],
    },
    x86asm => {
        feature: "lang-x86asm",
        name: "x86asm",
        ts_lang: arborium_x86asm::language(),
        node_types_key: "x86asm",
        names: ["x86asm", "x86"],
        extensions: ["asm"],
    },
    xml => {
        feature: "lang-xml",
        name: "xml",
        ts_lang: arborium_xml::language(),
        node_types_key: "xml",
        names: ["xml"],
        extensions: ["xml", "xsl", "xslt", "xsd", "svg"],
    },
    yaml => {
        feature: "lang-yaml",
        name: "yaml",
        ts_lang: arborium_yaml::language(),
        node_types_key: "yaml",
        names: ["yaml", "yml"],
        extensions: ["yaml", "yml"],
    },
    yuri => {
        feature: "lang-yuri",
        name: "yuri",
        ts_lang: arborium_yuri::language(),
        node_types_key: "yuri",
        names: ["yuri"],
        extensions: ["yuri"],
    },
    zig => {
        feature: "lang-zig",
        name: "zig",
        ts_lang: arborium_zig::language(),
        node_types_key: "zig",
        names: ["zig"],
        extensions: ["zig"],
    },
    zsh => {
        feature: "lang-zsh",
        name: "zsh",
        ts_lang: arborium_zsh::language(),
        node_types_key: "zsh",
        names: ["zsh"],
        extensions: ["zsh"],
    },
}
