use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

const GRAMMARS: &[(&str, &str)] = &[
    ("arborium_javascript", "JAVASCRIPT"),
    ("arborium_typescript", "TYPESCRIPT"),
    ("arborium_dart", "DART"),
];

fn main() {
    let manifest_dir =
        PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR must be set"));
    let metadata = cargo_metadata::MetadataCommand::new()
        .manifest_path(manifest_dir.join("Cargo.toml"))
        .exec()
        .expect("test dependencies must resolve");
    let package = metadata
        .packages
        .iter()
        .find(|package| package.manifest_path.as_std_path() == manifest_dir.join("Cargo.toml"))
        .expect("plotnik-tests package must be in cargo metadata");
    let resolve = metadata
        .resolve
        .as_ref()
        .expect("cargo metadata must include the dependency graph");
    let node = resolve
        .nodes
        .iter()
        .find(|node| node.id == package.id)
        .expect("plotnik-tests must be in the resolved dependency graph");

    for &(dependency, key) in GRAMMARS {
        let dependency_id = &node
            .deps
            .iter()
            .find(|candidate| candidate.name == dependency)
            .unwrap_or_else(|| panic!("direct dependency `{dependency}` must resolve"))
            .pkg;
        let found = metadata
            .packages
            .iter()
            .find(|candidate| candidate.id == *dependency_id)
            .unwrap_or_else(|| panic!("package `{dependency_id}` must be in cargo metadata"));
        let root = found
            .manifest_path
            .parent()
            .unwrap_or_else(|| panic!("{dependency} package must have a parent directory"));
        let grammar_path = root.join("grammar/src/grammar.json");
        if !grammar_path.is_file() {
            panic!("{dependency} grammar.json must exist at {grammar_path}");
        }

        println!("cargo::rustc-env=PLOTNIK_TEST_GRAMMAR_{key}={grammar_path}");
        println!("cargo::rerun-if-changed={grammar_path}");
    }

    generate_snapshot_tests(&manifest_dir);

    println!("cargo::rerun-if-changed=build.rs");
    println!("cargo::rerun-if-changed=Cargo.toml");
    println!(
        "cargo::rerun-if-changed={}",
        manifest_dir.join("../../Cargo.lock").display()
    );
}

fn generate_snapshot_tests(manifest_dir: &Path) {
    let tests_dir = manifest_dir.join("tests");
    let mut snapshots = Vec::new();
    discover_snapshots(&tests_dir, &tests_dir, &mut snapshots);
    snapshots.sort();

    let mut tests = TestModule::default();
    for relative in snapshots {
        tests.insert(&relative);
    }
    let mut generated = String::from("// @generated by crates/plotnik-tests/build.rs\n\n");
    tests.render(&mut generated, 0);

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR must be set"));
    let destination = out_dir.join("snapshot_tests.rs");
    let unchanged = fs::read_to_string(&destination).is_ok_and(|current| current == generated);
    if !unchanged {
        fs::write(destination, generated).expect("generated snapshot tests must be writable");
    }
    println!("cargo::rerun-if-changed={}", tests_dir.display());
}

fn discover_snapshots(dir: &Path, root: &Path, out: &mut Vec<String>) {
    let entries = fs::read_dir(dir)
        .unwrap_or_else(|error| panic!("read snapshot dir {}: {error}", dir.display()));
    for entry in entries {
        let entry = entry
            .unwrap_or_else(|error| panic!("read snapshot entry in {}: {error}", dir.display()));
        let path = entry.path();
        if path.is_dir() {
            discover_snapshots(&path, root, out);
            continue;
        }
        if path.extension().and_then(|extension| extension.to_str()) != Some("txt") {
            continue;
        }
        let relative = path
            .strip_prefix(root)
            .expect("snapshot path must be under tests/")
            .to_str()
            .unwrap_or_else(|| panic!("snapshot path is not UTF-8: {}", path.display()))
            .replace(std::path::MAIN_SEPARATOR, "/");
        let stage = relative.split('/').next().unwrap_or("");
        if is_stage_dir(stage) {
            out.push(relative);
        }
    }
}

fn is_stage_dir(name: &str) -> bool {
    let bytes = name.as_bytes();
    bytes.len() >= 3
        && bytes[0].is_ascii_digit()
        && bytes[1].is_ascii_digit()
        && bytes[2] == b'-'
        && !name.starts_with("01-")
}

#[derive(Default)]
struct TestModule {
    modules: BTreeMap<String, TestModule>,
    snapshots: BTreeMap<String, String>,
}

impl TestModule {
    fn insert(&mut self, relative: &str) {
        let mut components = relative.split('/').collect::<Vec<_>>();
        let file = components
            .pop()
            .expect("snapshot path must have a file name");
        let stem = file
            .strip_suffix(".txt")
            .expect("snapshot path must end in .txt");
        require_snake_case(stem, relative);

        let mut module = self;
        for (index, component) in components.into_iter().enumerate() {
            let identifier = if index == 0 {
                let identifier = format!("stage_{}", component.replace('-', "_"));
                require_snake_case(&identifier, relative);
                identifier
            } else {
                require_snake_case(component, relative);
                component.to_string()
            };
            module = module.modules.entry(identifier).or_default();
        }

        let identifier = format!("snapshot_{stem}");
        if let Some(previous) = module
            .snapshots
            .insert(identifier.clone(), relative.to_string())
        {
            panic!(
                "snapshot paths `{previous}` and `{relative}` both register Rust test `{identifier}`"
            );
        }
    }

    fn render(&self, generated: &mut String, depth: usize) {
        for (identifier, relative) in &self.snapshots {
            let indent = "    ".repeat(depth);
            writeln!(generated, "{indent}#[test]").expect("write generated test attribute");
            writeln!(
                generated,
                "{indent}fn {identifier}() -> Result<(), String> {{"
            )
            .expect("write generated test declaration");
            writeln!(generated, "{indent}    crate::run_snapshot({relative:?})")
                .expect("write generated test body");
            writeln!(generated, "{indent}}}\n").expect("write generated test close");
        }
        for (identifier, module) in &self.modules {
            let indent = "    ".repeat(depth);
            writeln!(generated, "{indent}mod {identifier} {{")
                .expect("write generated module declaration");
            module.render(generated, depth + 1);
            writeln!(generated, "{indent}}}\n").expect("write generated module close");
        }
    }
}

fn require_snake_case(component: &str, relative: &str) {
    let mut bytes = component.bytes();
    let valid_start = bytes
        .next()
        .is_some_and(|byte| byte.is_ascii_lowercase() || byte == b'_');
    let valid_rest =
        bytes.all(|byte| byte.is_ascii_lowercase() || byte.is_ascii_digit() || byte == b'_');
    if !valid_start || !valid_rest {
        panic!("snapshot path component `{component}` is not snake_case: {relative}");
    }
}
